spring:
    profiles:
        active: local #active local configuration

    jackson:
        property-naming-strategy: SNAKE_CASE

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update #auto generate sql
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format_sql: true

server:
    port: 1989
    servlet:
        context-path: /api/alpha.1.0
