spring:
    profiles:
        #active: local #active local configuration
        active: prod #active production configuration

    jackson:
        property-naming-strategy: SNAKE_CASE

server:
    port: 1989
    servlet:
        context-path: /api/alpha.1.0
